tasks:
  -  command: >
      npm install -g browser-sync &&
      browser-sync start -s -f . --no-notify --host $(gp url|sed 's/https\?:\/\///') --port 9000

ports:
  - port: 9000
    onOpen: open-browser
  - port: 3001
    onOpen: ignore
